### ISSUE TITLE
Travis CI Download for Linux...

### ISSUE THREAD

**Issue by rajabilal555** [maddinat0r/samp-discord-connector#10]
Where is the download link to .so(linux) files...
And .Inc files...
I see the AppVeyor [build's artifacts](https://ci.appveyor.com/project/maddinat0r/samp-discord-connector/branch/master/job/togfi82rqdu6glo8/artifacts), but it's for Windows (.DLL) where is the Linux (.so) build I can't get Travis CI builds artifact...
And download button in readme.md takes me to a missing page...

**Comment by maddinat0r** [comment]
Fixed the link, thanks!
TravisCI sadly doesn't provide this feature, so there's not much I can do here.

**Comment by rajabilal555** [comment]
But you may be able to 
publish Releases as I saw here...
[Stackoverflow-How to publish artifacts to Github...](http://stackoverflow.com/questions/12343452/how-to-publish-artifacts-in-travis-ci/24100779#24100779)

I am sure this will help a bit...

**Comment by maddinat0r** [comment]
Yeah, I know that you can automate releases through Travis CI (and probably also AppVeyor). That's actually a really nice feature, however I prefer to do this manually, because I compile plugins usually for more than one Linux distribution (e. g. when I compile the MySQL plugin, I always do a general Linux build, usually on Debian, and one on CentOS).

**Comment by rajabilal555** [comment]
So I need that build please make one at least you can tag it beta...
Because I need it and Can't Compile it either on LINUX(Debian) or Windows(which will be useless as my server is on LINUX)...

**Comment by maddinat0r** [comment]
I'll release a public beta anyway, you just have to wait a little longer until all known bugs and problems are fixed.
