### ISSUE TITLE
DCC_SetGuildRoleColor crashes the server & DCC_SetGuildMemberNickname doesn't work

### ISSUE THREAD

**Issue by bubyygh** [maddinat0r/samp-discord-connector#102]
Title.

Role color:
Script compiles with no warnings. Everything is correctly scripted, checked few times. But it crashes the server.

Nicknames:
Bot has administrator permissions. Should work, but it doesn't.

**Comment by bubyygh** [comment]
Update:

I get this in discord-connector.log when using DCC_SetGuildMemberNickname:

`[08/28/19 23:20:30] [ERROR] Error while retrieving HTTP PATCH response from '/api/v6/guilds/615320063519621216/members/271358133123678208': end of stream`

**Comment by maddinat0r** [comment]
Regarding role color: I made a mistake in the URL formatting (now fixed in b89a3e439ef8808d5b8228c658259e5523b86b4e). Feel free to try out the fixed build [here](https://ci.appveyor.com/project/maddinat0r/samp-discord-connector/builds/27055998) (choose BUILD_TYPE=Release, Image=Ubuntu for Linux or Image=Visual Studio for Windows, then click on artifacts).

Regarding nickname changing: Has the user you want to change the nickname of, a higher role than the bot, or is the server owner?

**Comment by bubyygh** [comment]
My bad. I was trying to change my nickname but I'm the server owner. Everything works now. Thank you
