### ISSUE TITLE
ability to disable log-core

### ISSUE THREAD

**Issue by Alasnkz** [maddinat0r/samp-discord-connector#116]
Title.

**Comment by markski1** [comment]
log-core has caused us more problems than it's worth. I don't understand what it does that printf() can't do. It makes building the plugin miserable and it makes server restarts harder because it keeps catching stuff like kill interruptions.

It should be entirely optional both here and in mysql plugin

**Comment by maddinat0r** [comment]
> Title.

This doesn't really say anything, and I'm obviously not going to take this issue serious without any reasoning.
<br>

> I don't understand what it does that printf() can't do.
It does
- log rotation based by file size and date
- `logprintf` redirection (refer to [Southclaw's nolog plugin](https://github.com/Southclaws/samp-nolog#why) on why you'd want that)
- runtime log control (log-core reacts to changes to the `log-config.yml` file while running)
<br>

> It makes building the plugin miserable 

Can you elaborate on that? The only extra steps on building a plugin with log-core is to download [the log-core package](https://github.com/maddinat0r/samp-log-core/releases) (the one without `-runtime` at the end) and refer to it when calling CMake (`cmake -Dlog-core_DIR="/log-core/cmake" <other options> ..`).
<br>

> it makes server restarts harder because it keeps catching stuff like kill interruptions

I'll assume you're talking about the signal handling on Linux. There are signal handlers installed for these signals:
- `SIGABRT`: sent on `abort()` calls, which are usually caused by failed assertions and abnormal program termination
- `SIGFPE`: sent on invalid arithmetic operations, like dividing by zero
- `SIGILL`: sent on executing an malformed, unknown or otherwise invalid instruction
- `SIGSEGV`: sent in case of a segmentation fault (for example on invalid memory access)
- `SIGINT`: sent on process interruption

You're probably talking about the `SIGINT` handling when you wrote "kill interruptions". I can see why you could be bothered by it, but there is a reason I'm catching that signal. Users stopping the server by pressing Ctrl + C will cause sending `SIGINT` to the SA-MP server process. The server doesn't handle that signal and shuts down ungracefully (i.e. without calling `OnGameModeExit`). This resembles crash-like behavior, and that's why log-core catches that signal and flushes all queued log messages before shutting down. The flush process can take a while, depending on how many messages are in that queue.
You can terminate the process immediately by sending `SIGKILL`. That's the universal signal for instantly terminating any process, and as a matter of fact can't be caught by programs.

<br>
I'm willing to listen and act on criticism and suggestions, but without any proper arguments on why I should remove/disable log-core, I won't be doing anything.

**Comment by Alasnkz** [comment]
>Can you elaborate on that? The only extra steps on building a plugin with log-core is to download the log-core package (the one without -runtime at the end) and refer to it when calling CMake (cmake -Dlog-core_DIR="/log-core/cmake" <other options> ..).

I'm not sure why this comment has better build instructions than the projects that use log-core itself. You should include this in the building guide rather than just linking them to the package and let them figure it out on their own.

**Comment by maddinat0r** [comment]
Yes, I'll definitely have to make it build easier altogether (#115). I already noticed that while I was trying to write better documentation for compiling it, and stopped when I got to step 12. However, log-core isn't the reason why building this plugin is currently that bad, it's more about OpenSSL.
