### ISSUE TITLE
Make a message queue

### ISSUE THREAD

**Issue by Zorono** [maddinat0r/samp-discord-connector#118]
Hello dude,
so it'd be great if you made an Discord Messages Queue(Caching related...) with other words:
when it says ```[12/12/2019 | 10:17:17]  >> plugin.dc-connector: timeout while initializing data.
[12/12/2019 | 10:17:17]                          plugin will proceed to retry connecting in the background.```
those messages which is requested to be sent by `DCC_* ` natives... must be queued to be sent when the connection to Discord API is done successfully...

**Comment by maddinat0r** [comment]
You shouldn't be able to send messages in the first place, because the data cache is completely empty until the plugin is properly initialized. That means doing any look-ups like `DCC_FindChannelByName` will return `DCC_INVALID_CHANNEL`. And that's why creating that message queue is not possible, as there isn't any information (apart from the text message you want to send) I could cache.
