### ISSUE TITLE
Wrong user's name after change

### ISSUE THREAD

**Issue by b4ll** [maddinat0r/samp-discord-connector#126]
Hi, the problem is with function `DCC_GetUserName`. When someone change name on discord (global name), then `DCC_GetUserName` returns a `Deleted account` string. I tried to leave and then connect again to the server but it didn't help. I'll post some images to show how it looks.

https://cdn.discordapp.com/attachments/613060346013286450/675445457006231554/unknown.png
https://cdn.discordapp.com/attachments/613060346013286450/675445220829036592/unknown.png

PAWN code

```
DCC_GetMessageContent(message, lMessage);
DCC_GetUserName(lAuthor, lName);
format(lString, 200, "[Discord] "C_INFORMATION"%s "C_WHITE"%s", lName, lMessage);
SendClientMessageToAll(-1, lString);
```

**Comment by mikescnr** [comment]
I'm having a similar problem, whereby their _old_ Discord global name is returned instead of their new one.

Here's what I did:
- On Discord as `James_Smith` (global name, no nick set).
- DCC_GetUserName returns `James_Smith` as it should.
- Changed my Discord global name to `Smith_James`.
- DCC_GetUserName is still returning the old name of `James_Smith`. It should be returning the new name of `Smith_James`.

Restarting the server fixes this as I assume the plugin loads user names into memory at startup. They need to be updated if a member changes their Discord global name.

This is currently causing me a very large headache as I have a script to set someone's nickname to match their in-game name, and you cannot set someone's nickname to the same as their global name. I have a player called 'Woo' (in-game and Discord global name) and their old Discord name 'Fa' is being returned by DCC_GetUserName. Therefore it thinks it can set their nickname to 'Woo' because Woo != Fa. But their name is actually Woo already so their nickname fails to be set. It then checks this again and again and keeps trying to set their nickname because logic says it should be able to be set, but the wrong name is being returned by DCC_GetUserName.

**Comment by Alasnkz** [comment]
Is this still an issue?
