### ISSUE TITLE
Build not linking Boost correctly

### ISSUE THREAD

**Issue by Southclaws** [maddinat0r/samp-discord-connector#2]
Not sure if this is an issue with the included CMake files or my system but I thought I'd raise an issue anyway because this happened after following the build steps in the readme (and also checking the Travis log).

Steps I took:
- Installed cmake-3.7.1
- Installed boost 1.6.3 (default location)
- `mkdir build && cd build && cmake ..`

Result:

```
$ cmake ..
CMake Warning at /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:744 (message):
  Imported targets not available for Boost version 106300
Call Stack (most recent call first):
  /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:848 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:1435 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:21 (find_package)


-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   system
-- CMake version: 3.7.1
-- Build type:
-- Configuring done
CMake Error at libs/cmake/AddSAMPPlugin.cmake:2 (add_library):
  Target "discord-connector" links to target "Boost::system" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_samp_plugin)


-- Generating done
-- Build files have been written to: /home/southclaws/samp-discord-connector/build
```

Once I can get this to build, I plan to use it in production so I'll likely be actively contributing!

**Comment by Southclaws** [comment]
Update: got it to link using
```
SET(Boost_INCLUDE_DIR "/home/southclaws/boost_1_59_0")
SET(BOOST_LIBRARYDIR  "/home/southclaws/boost_1_59_0/stage/lib")
```
So this could be closed however I think the readme should elaborate on this a bit for people not familiar with linking boost libraries. (I'm not even sure if this is the "correct" way to do this, I'm not familiar with CMake either!)

**Comment by maddinat0r** [comment]
The thing is, the CMake file responsible for finding Boost can't handle import targets for Boost version 1.62 and higher.
That means you have two options: use an older Boost version (like you already did; I don't recommend this however) or patch the correct CMake file (replace the one you have with the one [from CMake's master branch](https://github.com/Kitware/CMake/blob/master/Modules/FindBoost.cmake). That one has support for 1.62 (so yeah, use 1.62).

I also don't recommend using this plugin in production at the moment, since it certainly will crash your server at some point.

**Comment by Southclaws** [comment]
Alright, thanks! I'll sort it out anyway and play around with the plugin. I aim to help get it stable and ready for production!
