### ISSUE TITLE
Plugin does not conform to architecture 

### ISSUE THREAD

**Issue by TheDarknessz0rz** [maddinat0r/samp-discord-connector#36]
[01:55:24]  Loading plugin: discord-connector.so
[01:55:24]   Plugin does not conform to architecture.
[01:55:24]   Failed.

I've specified to force -m32 for all compilations, I don't know why this is happening.

**Comment by maddinat0r** [comment]
Sorry for the late reply.
You don't need to explicitly pass `-m32`. I've set up the CMake build to always add that flag.
I can't really say what you did wrong, as there's not enough information here. It probably doesn't matter anymore due to my very slow reply. I'll close this, but feel free to reopen this issue if you can't manage to compile it properly.
